# reuse in extends: https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/

services:
  generic:
    restart: unless-stopped
    hostname: ${nas_name}
    security_opt: [no-new-privileges:true]
    networks:
      - eden
    environment:
      DOCKER_API_VERSION: ${docker_api_version} # https://github.com/docker/cli/issues/2533
      TZ: ${timezone}

  genericReadOnly:
    extends:
      service: generic
    read_only: true

  genericReadOnlyAsContainerUserNoCap:
    extends:
      service: genericReadOnly
    user: ${uid}:${gid}
    cap_drop: [all] # Drop all Linux capabilities

  genericAsContainerUser:
    extends:
      service: generic
    user: ${uid}:${gid}

  private:
    extends:
      service: generic
    labels:
      caddy_0.@denied.not_0: "remote_ip ${private_ip_range}"
      caddy_0.abort: "@denied"

  privateReadOnly:
    extends:
      service: private
    read_only: true

  privateReadOnlyAsContainerUserNoCap:
    extends:
      service: privateReadOnly
    user: ${uid}:${gid}
    cap_drop: [all] # Drop all Linux capabilities

  privateAsContainerUser:
    extends:
      service: private
    user: ${uid}:${gid}

  privateAsEnvironmentUser:
    extends:
      service: private
    environment:
      PUID: ${uid}
      PGID: ${gid}
