# reuse in extends: https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/

services:
  generic:
    restart: unless-stopped
    hostname: ${nas_name}
    networks:
      - eden
    environment:
      DOCKER_API_VERSION: ${docker_api_version} # https://github.com/docker/cli/issues/2533
      TZ: ${timezone}

  private:
    extends:
      service: generic
    labels:
      caddy_0.@denied.not_0: "remote_ip ${private_ip_range}"
      caddy_0.abort: "@denied"

  public:
    extends:
      service: generic
