# reuse in extends: https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/

services:
  generic:
    restart: unless-stopped
    hostname: ${nas_name}
    networks:
      - eden
    environment:
      TZ: ${timezone}

  private:
    restart: unless-stopped
    hostname: ${nas_name}
    networks:
      - eden
    environment:
      TZ: ${timezone}
    labels:
      caddy_0.@denied.not_0: "remote_ip ${private_ip_range}"
      caddy_0.abort: "@denied"

  public:
    restart: unless-stopped
    hostname: ${nas_name}
    networks:
      - eden
    environment:
      TZ: ${timezone}
