services:
  code-server-dotnet:
    container_name: code
    image: ptr727/vscode-server-dotnetcore:latest
    extends:
      file: ../docker-common/base.yaml
      service: privateAsEnvironmentUser
    environment:
      DEFAULT_WORKSPACE: /config/workspace
    volumes:
      - ${host_data_config_path}/codeserver:/config
    labels:
      caddy_0: ${private_protocol}code.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 8443}}"
      caddy_0.import: tinyauth_forwarder *
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:18-alpine
    extends:
      file: ../docker-common/base.yaml
      service: genericAsContainerUser #accesses /var/run/postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/interface_pw
      POSTGRES_DB: nasi
      PGPORT: 6432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d nasi -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ${host_data_config_path}/postgres/data:/var/lib/postgresql/18/docker
      - ${host_data_config_path}/postgres/scripts:/docker-entrypoint-initdb.d/
      - /etc/passwd:/etc/passwd:ro # see https://github.com/docker-library/docs/blob/master/postgres/README.md#arbitrary---user-notes
    secrets:
      - interface_pw
    labels:
      caddy_0.layer4.:6432:
      caddy_0.layer4.:6432.@a: "remote_ip ${private_ip_range}"
      caddy_0.layer4.:6432.route: "@a"
      caddy_0.layer4.:6432.route.proxy: "{{ upstreams 6432 }}"

  coredns:
    container_name: coredns
    image: coredns/coredns:latest
    extends:
      file: ../docker-common/base.yaml
      service: genericAsContainerUser
    volumes:
      - ${host_data_config_path}/coredns/:/coredns-config/
    command: -conf coredns-config/Corefile
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 5533:53/udp

  ibm-mq:
    container_name: ibmmq
    image: icr.io/ibm-messaging/mq:latest
    extends:
      file: ../docker-common/base.yaml
      service: generic
    user: ${uid}
    ports:
      - 9443:9443 # Expose it directly because we cannot disable the HTTPS endpoint in the container easily
    group_add:
      - ${gid} # https://github.com/ibm-messaging/mq-container/issues/601
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_ADMIN_PASSWORD: admin
    volumes: # https://www.ibm.com/docs/en/ibm-mq/9.4.x?topic=reference-mq-advanced-container-image#container-image-ref__file-system-mount-points__title__1
      - ../docker-ibmmq/configure.mqsc:/etc/mqm/configure.mqsc
      - ../docker-ibmmq/mykey:/etc/mqm/pki/keys/mykey
      - ${host_data_config_path}/ibmmq/:/mnt/mqm
    labels:
      caddy_0: ${private_protocol}ibmmq.${private_domain} # https://github.com/ibm-messaging/mq-container/issues/443
      caddy_0.reverse_proxy: "{{upstreams 9443}}"
      caddy_0.import: tinyauth_forwarder *
      caddy_1.layer4.:1414:
      caddy_1.layer4.:1414.@a: "remote_ip ${private_ip_range}"
      caddy_1.layer4.:1414.route: "@a"
      caddy_1.layer4.:1414.route.proxy: "{{ upstreams 1414 }}"

  envoy-proxy:
    container_name: envoy-proxy
    image: envoyproxy/envoy:distroless-v1.37-latest
    extends:
      file: ../docker-common/base.yaml
      service: privateReadOnlyAsContainerUserNoCap
    environment:
      ENVOY_UID: ${uid}
      ENVOY_GID: ${gid}
    volumes:
      - ${host_data_config_path}/envoy/:/etc/envoy/
    command: ["--concurrency", "1", "-c", "/etc/envoy/demo.yaml"]
    labels:
      caddy_0: ${private_protocol}envoy-admin.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 9901}}"
      caddy_0.import: tinyauth_forwarder *
      caddy_1: ${private_protocol}envoy.${private_domain}
      caddy_1.reverse_proxy: "{{upstreams 10000}}"

  apicurio:
    container_name: apicurio
    image: apicurio/apicurio-registry:latest-release
    extends:
      file: ../docker-common/base.yaml
      service: privateAsContainerUserNoCap
    environment:
      QUARKUS_HTTP_CORS_ORIGINS: "*"
      REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED: "true"
      APICURIO_DATASOURCE_URL: 'jdbc:postgresql://postgres:6432/nasi'
      APICURIO_DATASOURCE_USERNAME: admin
      APICURIO_DATASOURCE_PASSWORD: 106243
      APICURIO_STORAGE_KIND: "sql"
      APICURIO_STORAGE_SQL_KIND: "postgresql"
    labels:
      caddy_0: ${private_protocol}apicurio-api.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 8080}}"

  apicurio-ui:
    container_name: apicurio-ui
    image: apicurio/apicurio-registry-ui:latest-release
    extends:
      file: ../docker-common/base.yaml
      service: private
    environment:
      REGISTRY_API_URL: ${private_protocol}apicurio-api.${private_domain}/apis/registry/v3
    labels:
      caddy_0: ${private_protocol}apicurio.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 8080}}"
      caddy_0.import: tinyauth_forwarder *
    depends_on:
      - apicurio

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    extends:
      file: ../docker-common/base.yaml
      service: privateAsContainerUserNoCap
    volumes:
      - ${host_data_config_path}/node-red/:/data
    labels:
      caddy_0: ${private_protocol}node-red.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 1880}}"
      caddy_0.import: tinyauth_forwarder *