services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/jellyfin/jellyfin:latest
    extends:
      file: ../docker-common/base.yaml
      service: privateAsContainerUserNoCap
    environment:
      JELLYFIN_PublishedServerUrl: ${private_protocol}jellyfin.${private_domain}:80
    volumes:
      - ${host_data_config_path}/jellyfin/cache:/cache
      - ${host_data_config_path}/jellyfin/config:/config
      - ${host_data_media_path}:/media:ro
    group_add:
      - ${vgid}
    labels:
      caddy_0: ${private_protocol}jellyfin.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 8096}}"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

  # run following in order to convert DV Profile 7 to DV Profile 8 and delete the original:
  # dovi -batch -include-simple -r -y -delete
  #
  # or just scan for DV Profile 7 files:
  # dovi -scan -r
  dovi_convert:
    container_name: dovi_convert
    image: cryptochrome/dovi_convert:latest
    extends:
      file: ../docker-common/base.yaml
      service: privateAsEnvironmentUser
    volumes:
      - ${host_data_media_path}:/data
    labels:
      caddy_0: ${private_protocol}dovi.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 7681}}"
      caddy_0.import: tinyauth_forwarder *

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    extends:
      file: ../docker-common/base.yaml
      service: privateAsEnvironmentUser
    volumes:
      - ${host_data_config_path}/prowlarr:/config
    labels:
      caddy_0: ${private_protocol}prowlarr.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 9696}}"
      caddy_0.import: tinyauth_forwarder *

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    extends:
      file: ../docker-common/base.yaml
      service: privateAsEnvironmentUser
    volumes:
      - ${host_data_config_path}/radarr:/config
      - ${host_data_path}:/data
    labels:
      caddy_0: ${private_protocol}radarr.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 7878}}"
      caddy_0.import: tinyauth_forwarder *

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    extends:
      file: ../docker-common/base.yaml
      service: privateAsEnvironmentUser
    environment:
      UMASK: 002
      WEBUI_PORTS: 6767/tcp,6767/udp
    volumes:
      - ${host_data_config_path}/bazarr:/config
      - ${host_data_path}:/data
    labels:
      caddy_0: ${private_protocol}bazarr.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 6767}}"
      caddy_0.import: tinyauth_forwarder *

  qbittorrent:
    container_name: qbittorrent
    image: qbittorrentofficial/qbittorrent-nox:latest
    extends:
      file: ../docker-common/base.yaml
      service: privateAsContainerUserNoCap
    environment:
      QBT_WEBUI_PORT: 32500
      QBT_LEGAL_NOTICE: confirm
      QBT_VERSION: latest
      QBT_DOWNLOADS_PATH: /data/downloads
    tmpfs:
      - /tmp
    volumes:
      - ${host_data_config_path}:/config
      - ${host_data_path}:/data
    labels:
      caddy_0: ${private_protocol}qbittorrent.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 32500}}"
      caddy_0.import: tinyauth_forwarder *
      caddy_1.layer4.:50777:
      caddy_1.layer4.:50777.@a: "remote_ip 0.0.0.0/0"
      caddy_1.layer4.:50777.route: "@a"
      caddy_1.layer4.:50777.route.proxy: "{{ upstreams 50777 }}"
