services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    user: ${uid}:${gid}
    extends:
      file: ../docker-common/base.yaml
      service: private
    environment:
      - JELLYFIN_PublishedServerUrl=${private_protocol}jellyfin.${private_domain}:80
    volumes:
      - ${host_data_config_path}/jellyfin/cache:/cache
      - ${host_data_config_path}/jellyfin/config:/config
      - ${host_data_media_path}:/media
    group_add:
      - ${vgid}
    labels:
      caddy_0: ${private_protocol}jellyfin.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 8096}}"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

  qbittorrent:
    container_name: qbittorrent
    image: qbittorrentofficial/qbittorrent-nox:latest
    extends:
      file: ../docker-common/base.yaml
      service: private
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - QBT_WEBUI_PORT=32500
      - QBT_LEGAL_NOTICE=confirm
      - QBT_VERSION=latest
      - QBT_DOWNLOADS_PATH=/media
    tmpfs:
      - /tmp
    volumes:
      - ${host_data_config_path}:/config
      - ${host_data_media_path}:/media
      - ${host_data_downloads_path}:/downloads
    labels:
      caddy_0: ${private_protocol}qbittorrent.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 32500}}"
      caddy_1.layer4.:50777:
      caddy_1.layer4.:50777.@a: "remote_ip 0.0.0.0/0"
      caddy_1.layer4.:50777.route: "@a"
      caddy_1.layer4.:50777.route.proxy: "{{ upstreams 50777 }}"
