services:
  whoami:
    container_name: whoami
    image: traefik/whoami:latest
    extends:
      file: ../docker-common/base.yaml
      service: private
    environment:
      WHOAMI_PORT_NUMBER: 708
    labels:
      caddy_0: ${private_protocol}whoami.${private_domain}
      caddy_0.reverse_proxy: "{{upstreams 708}}"
      caddy_1: ${public_protocol}whoami.${public_domain}
      caddy_1.reverse_proxy: "{{upstreams 708}}"
