services:
  whoami-public:
    container_name: whoami-public
    image: traefik/whoami:latest
    extends:
      file: ../docker-common/base.yaml
      service: public
    environment:
      - WHOAMI_PORT_NUMBER=707
    labels:
      caddy: ${public_protocol}whoami.${public_domain}
      caddy.reverse_proxy: "{{upstreams 707}}"

  whoami-private:
    container_name: whoami-private
    image: traefik/whoami:latest
    extends:
      file: ../docker-common/base.yaml
      service: private
    environment:
      - WHOAMI_PORT_NUMBER=708
    labels:
      caddy: ${private_protocol}whoami.${private_domain}
      caddy.reverse_proxy: "{{upstreams 708}}"
