name: garden

secrets:
  interface_pw:
    file: ./secrets/interface_pw.txt
  github_client_secret:
    file: ./secrets/github_client_secret.txt
  tinyauth_cookie_secret:
    file: ./secrets/tinyauth_cookie_secret.txt
  cloudflare_api_token:
    file: ./secrets/cloudflare_api_token.txt

# Includes aren't fully supported in Synology yet, the first time you import this compose file, comment the 'includes' below and save it, then uncomment it.
include:
  - ./docker-services/infra.yaml
  - ./docker-services/observability.yaml
  - ./docker-services/media.yaml
  - ./docker-services/ide.yaml
