name: garden

secrets:
  interface_pw:
    file: ./secrets/interface_pw.txt

include:
  - ./docker-services/infra.yaml
  - ./docker-services/observability.yaml
  - ./docker-services/media.yaml
  - ./docker-services/ide.yaml
